### ISSUE TITLE
Restructure code into suitable folders and contracts 

### ISSUE THREAD

**Issue by langnavina97** [Velvet-Capital/protocols#30]
- Creation of several contracts organized into different folders (split the code into suitable contracts) 
- Creation of Core (index itself including index token calculation which represents the share in a portfolio), Libraries, additional features such as rebalancing, etc.

**Comment by langnavina97** [comment]
Created a new branch with a new structure: fa-split-code-into-several-contracts](https://github.com/Velvet-Capital/protocols/tree/fa-split-code-into-several-contracts

Test cases of rebalance are currently failing (VM Exception while processing transaction: reverted with reason string 'TransferHelper::transferFrom: transferFrom failed' in sellTokens() - IndexManager._swapTokenToETH

AccessControl has to be done to restrict function calls of IndexManager

**Comment by aj07** [comment]
@aj07 @bcryptop2p @skadoosh-dev
