### ISSUE TITLE
Index calculation after adding fee module

### ISSUE THREAD

**Issue by langnavina97** [Velvet-Capital/protocols#43]
User 1 invests 100 BNB today, User 2 invests 100 BNB in 7 days
Vault value on Day 7: 100 BNB - (fee percentage / 30) * 7
When user 2 invests we're calculating the mint amount of index token with 100 BNB
--> share of user 2 should be larger than share of user 1 (assume the market does not change)

We have to make sure the calculation of the index token to mint considers the decreasing value of the portfolio according to fees

**Comment by aj07** [comment]
Is this resolved @langnavina97  ?

**Comment by langnavina97** [comment]
No, this will be for V2. For now we have only the simple feeModule @aj07
