### ISSUE TITLE
Flashloan based Price Oracle Manipulation [PVE003]

### ISSUE THREAD

**Issue by TusharTapadia** [Velvet-Capital/protocols#56]
I guess this can be solved by using an external source to get price.

**Comment by sagarjethi** [comment]
https://github.com/Uniswap/v2-periphery/blob/master/contracts/examples/ExampleOracleSimple.sol

https://github.com/Uniswap/v2-periphery/blob/master/contracts/examples/ExampleOracleSimple.sol

**Comment by TusharTapadia** [comment]
![IMG_6019](https://user-images.githubusercontent.com/53835566/179513207-4887c651-67b6-484a-af80-d8ed74262967.JPG)
