### ISSUE TITLE
Refactory code

### ISSUE THREAD

**Issue by sagarjethi** [Velvet-Capital/protocols#7]
- Example- current code we have taken variables each asset token(amount1, amount2)
- We should optimize the gas fee
- Make the code base generic so only the tokens have to be initialized and make it work for x amount of tokens
- remove unnecessary code and if statements

**Comment by aj07** [comment]
@sagarjethi can you please name the specific function name along with little bit more description where its required. It will be easy for us to quickly go through it.

While raising the issue there is a format coming by default. Would be nice if we can follow the format :)

**Comment by langnavina97** [comment]
@sagarjethi I refactored the code base but there still seems to be an issue with the amounts array. The first investment works fine, but the second one fails.
